name: bitcoin_bip44
version: 0.1.1
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32

dependencies:
    bitcoin_bip32: ^0.1.1
    bech32: ^0.1.2
    http: ^0.12.0+2
    pointycastle: ^1.0.1

dev_dependencies:
    test: ^1.9.3
    hex: ^0.1.2
    mock_web_server:
        git:
            url: git://github.com/haarts/MockWebServer.git
            ref: f8079e9f52ac45d920c677e545316a6905eaf819


environment:
    sdk: ">=2.4.0 <3.0.0"
